In [1]:
import numpy as np
import sys
import os

os.chdir('../')
from zodi_model.get_zmod import get_zmod
from zodi_model.solar_sp import solar_sp

# import sys
sys.path.append('/Applications/harris/idl89/lib/bridges')
from idlpy import *

new_dir = '/Users/rosaliaobrien/skysurf/github/skysurf/Zodiacal_Light_Model_IDL/'
os.chdir(new_dir)

IDL.run('.compile get_zmod')

IDL 8.9.0 (darwin x86_64 m64).
(c) 2023, L3Harris Geospatial Solutions, Inc.

Licensed for use by: Arizona State University
License: 496062
% Compiled module: ASTROLIB.
% ASTROLIB: Astronomy Library system variables have been added


'% Compiled module: STRNUMBER.\n% Compiled module: REPCHR.\n% Compiled module: REMCHAR.\n% Compiled module: GETTOK.\n% Compiled module: ZPARCHECK.\n% Compiled module: FDECOMP.\n% Compiled module: BINSRCH.\n% Compiled module: ANYWHERE.\n% Compiled module: NOWHERE.\n% Compiled module: READCOL.\n% Compiled module: CONFINT.\n% Compiled module: HONG_PHASE_FUNC.\n% Compiled module: GET_PHASE_INTEGRAL.\n% Compiled module: GET_ALBEDO.\n% Compiled module: GET_MULT.\n% Compiled module: GET_EMISS.\n% Compiled module: GET_HONG_PARAMS.\n% Compiled module: GAUSSINT.\n% Compiled module: SIMPINT.\n% Compiled module: EARTHSUN.\n% Compiled module: COLCORR.\n% Compiled module: ZPLANCK.\n% Compiled module: THERMFUNC.\n% Compiled module: PHASEFUNC.\n% Compiled module: SCATTFUNC.\n% Compiled module: ZSRCFUNC.\n% Compiled module: ZCLOUD.\n% Compiled module: MIGBAND.\n% Compiled module: SOLRING.\n% Compiled module: NEW_ISOCLOUD.\n% Compiled module: GET_PARNAMES.\n% Compiled module: GET_PARINDEX.\n% Compiled m

In [2]:
zodi_python = get_zmod(1.7, 'skysurf', 100, 0, 90)
zodi_python

array([0.1027667])

In [3]:
wavelength_arr = np.random.uniform(0.2,3.5,100)
day_arr = np.random.uniform(0,365,100)
lon_arr = np.random.uniform(0,360,100)
lat_arr = np.random.uniform(-90,90,100)
wavelength_arr

array([2.70476021, 2.40273073, 0.23656559, 0.3968873 , 1.80787074,
       3.38521857, 2.01868812, 2.51522002, 1.65824148, 2.66189848,
       2.62430916, 2.66398594, 1.31436529, 0.28659476, 2.45290109,
       0.58218827, 2.65773567, 1.88918591, 0.4012835 , 2.30253247,
       1.1321981 , 0.54431794, 0.48878753, 3.09320563, 2.63735276,
       2.56255695, 1.86671361, 3.00886867, 0.54823276, 2.01016645,
       1.10769773, 1.1206091 , 1.31864723, 1.24825937, 2.9599826 ,
       0.79439447, 2.78049805, 2.81988358, 2.07861023, 2.59582804,
       0.79449596, 2.9232011 , 3.30694159, 3.05658797, 1.23678492,
       2.80866238, 1.64774121, 0.66620453, 3.01821493, 1.08105976,
       0.41130858, 0.6688213 , 1.22860911, 0.29253188, 1.72484166,
       0.49630697, 1.34893681, 3.21883853, 0.37701631, 0.4559767 ,
       0.40660272, 0.63114829, 1.56114822, 1.69785557, 1.73065121,
       2.8018956 , 1.52994711, 2.20870027, 0.88803696, 3.43277121,
       2.37154162, 2.78682375, 1.43616101, 0.30967421, 2.00914

In [4]:
ratio_list = []

for wave in wavelength_arr:

    IDL.wave = wave
    IDL.day = day_arr
    IDL.lon = lon_arr
    IDL.lat = lat_arr
    
    idl_run_str = "zodi = get_zmod(wave,'skysurf',day,lon,lat)"
    IDL.run(idl_run_str)
    
    zodi_python = get_zmod(wave, 'skysurf', day_arr, lon_arr, lat_arr)
    
    ratio = IDL.zodi/zodi_python
    
    # Find indices where ratio is too high or too low
    bad_high = [i for i, r in enumerate(ratio) if r > 1.00001]
    bad_low  = [i for i, r in enumerate(ratio) if r < 0.99999]

    if bad_high or bad_low:
        print(f"\nBad wave: {wave}")

        print('\n')
        for i in bad_high:
            print('Zodi Python:', zodi_python[i])
            print('Zodi IDL:', IDL.zodi[i])
            print('Percent err:', (1-ratio[i])*100)
            print('Day:', day_arr[i])
            print('Lon:', lon_arr[i])
            print('Lat:', lat_arr[i])
            print('\n')

        print('\n')
        for i in bad_low:
            print('Zodi Python:', zodi_python[i])
            print('Zodi IDL:', IDL.zodi[i])
            print('Percent err:', (1-ratio[i])*100)
            print('Day:', day_arr[i])
            print('Lon:', lon_arr[i])
            print('Lat:', lat_arr[i])
            print('\n')

        # print('\n')


Bad wave: 0.29253187858575025




Zodi Python: 0.0058274
Zodi IDL: 0.0058273
Percent err: 0.0017197228788901064
Day: 194.1897381722865
Lon: 202.11713978697804
Lat: -56.22970639344728



Bad wave: 0.3096742149006277




Zodi Python: 0.0053734
Zodi IDL: 0.0053733
Percent err: 0.0018600294177995025
Day: 253.2236016153044
Lon: 354.51916220752673
Lat: -70.41318883031076



Bad wave: 0.24673416615145144




Zodi Python: 0.0013564
Zodi IDL: 0.0013563
Percent err: 0.0073749208408191436
Day: 54.314151958464706
Lon: 289.96986333958273
Lat: -49.91625174187809




In [5]:
ratio

array([1.        , 0.99999997, 1.        , 1.00000001, 0.99999962,
       1.        , 1.00000002, 1.        , 0.99999887, 0.99999998,
       1.00000004, 1.00000005, 1.        , 1.00000001, 0.99999998,
       0.99999999, 0.99999999, 0.99999997, 1.00000002, 1.00000002,
       0.99999997, 1.00000001, 0.99999998, 0.99999871, 0.99999787,
       0.9999987 , 1.00000126, 0.9999994 , 1.00000002, 1.        ,
       0.99999955, 1.        , 0.99999858, 0.99999997, 1.00000019,
       1.00000004, 1.00000004, 1.00000097, 1.        , 1.00000001,
       0.99999998, 1.00000049, 1.00000001, 1.00000002, 0.99999997,
       0.99999998, 1.00000004, 1.00000005, 0.99999998, 1.00000002,
       1.        , 1.00000002, 0.99999998, 1.00000053, 1.00000001,
       0.99999998, 1.00000094, 1.00000091, 1.00000001, 1.00000002,
       0.99999998, 1.00000003, 1.00000004, 0.99999998, 1.0000007 ,
       0.99999998, 0.99999999, 0.99999997, 1.00000001, 1.00000003,
       1.00000057, 1.00000258, 0.99999761, 1.00000114, 1.00000

In [6]:
IDL.lam_list

In [7]:
IDL.run('get_mult(1.7)')

'       1.0378333'

In [8]:
def get_mult(wavelength):
    """
    Get multiplicative factor for wavelengths > 1.6 microns.
    From O'Brien+2025 - exact implementation from IDL code.
    Should be = 1 for nominal HST wavelengths. When extrapolating out to 3.5 micron,
    a multiplier is added to match Kelsall better.

    Parameters:
    -----------
    wavelength : float
        Wavelength in microns

    Returns:
    --------
    float
        Multiplicative factor
    """
    if wavelength > 1.6:
        # Define wavelength and corresponding multiplier arrays
        lam_list = np.array([1.6, 2.2, 3.5, 4.9])
        mult_list = np.array([1.0, 1.227, 1.259, 1.0])

        # Interpolate between known values
        mult = np.interp(wavelength, lam_list, mult_list)
    else:
        mult = 1.0

    return mult

get_mult(1.7)

1.0378333333333334

In [9]:
np.array([1,2,3,4,5])[-2:]

array([4, 5])

In [10]:
IDL.test = np.array([1,2,3,4,5])
IDL.run('test[-2:*]')

'                     4                     5'

In [11]:
def solar_sp(wl):
    """
    Get solar spectrum estimate for any HST filter wavelength.
    
    Parameters:
    -----------
    wl : float
        Filter pivot wavelength in microns
        
    Returns:
    --------
    float
        Solar irradiance flux corresponding to the wavelength
    """
    
    # Solar spectrum flux values from Meftah+2018 processed through synphot
    flux_list = np.array([
        342116.01092185226, 3303413.8230211968, 16446170.76831905, 38540384.25308177,
        76676420.67245902, 128397575.82048588, 163383841.02144498, 188032128.2839162,
        209709058.79870653, 222817547.04015842, 231397146.5020066, 236879895.06999975,
        240377633.42061776, 240102828.21749556, 240207441.71584302, 242311737.400332,
        242466975.45810118, 239266492.1652165, 236012167.31356388, 234112458.3463153,
        232315803.03923738, 230486116.59469134, 228286915.55386606, 226470781.5675577,
        223402900.34007382, 219638777.2725546, 216293016.7440792, 211500303.47740474,
        206744275.87123755, 202388213.20880648, 194714148.80128816, 186491553.63645998,
        177695555.54650787, 169120143.4729226, 163038749.8826924, 157660709.24363747,
        152858997.50144997, 147567784.00121564, 141494800.9698657, 135587161.29024366,
        130968090.05460267, 126572711.4813484, 121667103.66006078, 117232006.96815938,
        113448941.49968067, 109595246.1106673, 105537099.95096199, 103058055.50303835,
        99379501.93762545, 96338608.89280608, 93978899.84951772, 91222947.61009558,
        88494034.69464864, 85855255.29991786, 83237630.65178712, 80917313.50268097,
        78438109.93458664, 76117181.55382372, 74046645.75447144, 71958356.82435888,
        70000915.22051653, 67960181.97848928, 65991330.90663976, 64262513.86657177,
        62599709.059710115, 61039646.51628048, 59535442.99040781, 57995180.64472865,
        56538132.5450691, 54990222.928732604, 53279644.45365265, 51993377.04684624,
        51031913.94275863, 49913322.053653, 48775552.520917535, 47584260.20074189,
        46383888.86630086, 45302398.118123665, 44374444.84588014, 43480870.197572455,
        42490931.52814285, 41500955.54348326, 40234353.02419229, 38724737.066997886,
        37359951.193162344, 36334960.86158876, 35511400.330898605, 34751678.18804755,
        34121176.04899815, 33525768.40115048, 33015642.888192605, 32516552.75856839,
        31972881.618588552, 31435922.631614495
    ])
    
    # Corresponding wavelengths in microns
    wave_list = np.array([
        0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85,
        0.9, 0.95, 1.0, 1.05, 1.1, 1.15, 1.2, 1.25, 1.3, 1.35, 1.4, 1.45, 1.5, 1.55,
        1.6, 1.65, 1.7, 1.75, 1.8, 1.85, 1.9, 1.95, 2.0, 2.05, 2.1, 2.15, 2.2, 2.25,
        2.3, 2.35, 2.4, 2.45, 2.5, 2.55, 2.6, 2.65, 2.7, 2.75, 2.8, 2.85, 2.9, 2.95,
        3.0, 3.05, 3.1, 3.15, 3.2, 3.25, 3.3, 3.35, 3.4, 3.45, 3.5, 3.55, 3.6, 3.65,
        3.7, 3.75, 3.8, 3.85, 3.9, 3.95, 4.0, 4.05, 4.1, 4.15, 4.2, 4.25, 4.3, 4.35,
        4.4, 4.45, 4.5, 4.55, 4.6, 4.65, 4.7, 4.75, 4.8, 4.85
    ])
    
    # Find closest wavelength
    diff_arr = np.abs(wave_list - wl)
    idx = np.argmin(diff_arr)
    # print(idx)
    return flux_list[idx]

python_sol_val = solar_sp(1.69381)

In [12]:
IDL.run('sol_val = solar_sp(1.69381)')

In [13]:
python_sol_val/IDL.sol_val

1.0000000246581375