In [1]:
import numpy as np
import sys
import os

os.chdir('../')
from zodi_model.get_zmod import get_zmod
from zodi_model.solar_sp import solar_sp

# import sys
sys.path.append('/Applications/harris/idl89/lib/bridges')
from idlpy import *

new_dir = '/Users/rosaliaobrien/skysurf/github/skysurf/Zodiacal_Light_Model_IDL/'
os.chdir(new_dir)

IDL.run('.compile get_zmod')

IDL 8.9.0 (darwin x86_64 m64).
(c) 2023, L3Harris Geospatial Solutions, Inc.

Licensed for use by: Arizona State University
License: 496062
% Compiled module: ASTROLIB.
% ASTROLIB: Astronomy Library system variables have been added


'% Compiled module: STRNUMBER.\n% Compiled module: REPCHR.\n% Compiled module: REMCHAR.\n% Compiled module: GETTOK.\n% Compiled module: ZPARCHECK.\n% Compiled module: FDECOMP.\n% Compiled module: BINSRCH.\n% Compiled module: ANYWHERE.\n% Compiled module: NOWHERE.\n% Compiled module: READCOL.\n% Compiled module: CONFINT.\n% Compiled module: HONG_PHASE_FUNC.\n% Compiled module: GET_PHASE_INTEGRAL.\n% Compiled module: GET_ALBEDO.\n% Compiled module: GET_MULT.\n% Compiled module: GET_EMISS.\n% Compiled module: GET_HONG_PARAMS.\n% Compiled module: GAUSSINT.\n% Compiled module: SIMPINT.\n% Compiled module: EARTHSUN.\n% Compiled module: COLCORR.\n% Compiled module: ZPLANCK.\n% Compiled module: THERMFUNC.\n% Compiled module: PHASEFUNC.\n% Compiled module: SCATTFUNC.\n% Compiled module: ZSRCFUNC.\n% Compiled module: ZCLOUD.\n% Compiled module: MIGBAND.\n% Compiled module: SOLRING.\n% Compiled module: NEW_ISOCLOUD.\n% Compiled module: GET_PARNAMES.\n% Compiled module: GET_PARINDEX.\n% Compiled m

In [2]:
zodi_python = get_zmod(1.7, 'skysurf', 100, 0, 90)
zodi_python

array([0.10277])

In [3]:
wavelength_arr = np.random.uniform(0.2,3.5,100)
day_arr = np.random.uniform(0,365,100)
lon_arr = np.random.uniform(0,360,100)
lat_arr = np.random.uniform(-90,90,100)
wavelength_arr

array([3.03120891, 1.67832794, 2.16242699, 0.97471452, 0.80489795,
       1.50696928, 2.7479882 , 0.98398382, 2.2153366 , 0.7293625 ,
       2.94111323, 1.40617054, 0.81681992, 1.68331573, 2.17341504,
       2.45841872, 2.75935146, 0.80340543, 0.8212599 , 2.75695961,
       2.21482162, 0.82408308, 2.51259901, 2.12295086, 2.50375715,
       3.0644908 , 2.42364751, 0.67882154, 0.66656593, 2.09277015,
       1.36749285, 2.67914037, 2.3474499 , 2.90937576, 2.66432427,
       2.53107028, 2.20714821, 1.45313271, 2.01936793, 0.44043456,
       2.48865452, 2.91828229, 0.4445032 , 0.44278314, 0.63836759,
       1.35741222, 3.35608222, 1.08167731, 0.90422879, 1.66990335,
       2.09447578, 0.5795654 , 1.33628335, 2.17611297, 1.32496799,
       3.21236671, 2.06592617, 2.73160565, 0.53925456, 0.60855078,
       2.42064257, 1.1410657 , 1.1742135 , 2.03954549, 0.88739869,
       0.38112919, 0.50700178, 1.61003325, 1.06166173, 0.24473884,
       3.02513669, 1.04957961, 0.99632802, 0.36397722, 2.57240

In [8]:
ratio_list = []

for wave in wavelength_arr:

    wave = np.round(wave, 5)

    IDL.wave = wave
    IDL.day = day_arr
    IDL.lon = lon_arr
    IDL.lat = lat_arr
    
    idl_run_str = "zodi = get_zmod(wave,'skysurf',day,lon,lat,new_iso_comp=1,iso_comp_only=1)"
    IDL.run(idl_run_str)
    
    zodi_python = get_zmod(wave, 'skysurf', day_arr, lon_arr, lat_arr, new_iso_comp=True, iso_comp_only=True)
    
    ratio = IDL.zodi/zodi_python
    
    # Find indices where ratio is too high or too low
    bad_high = [i for i, r in enumerate(ratio) if r > 1.00001]
    bad_low  = [i for i, r in enumerate(ratio) if r < 0.99999]

    if bad_high or bad_low:
        print(f"\nBad wave: {wave}")

        print('\n')
        for i in bad_high:
            print('Zodi Python:', zodi_python[i])
            print('Zodi IDL:', IDL.zodi[i])
            print('Percent err:', (1-ratio[i])*100)
            print('Day:', day_arr[i])
            print('Lon:', lon_arr[i])
            print('Lat:', lat_arr[i])
            print('\n')

        print('\n')
        for i in bad_low:
            print('Zodi Python:', zodi_python[i])
            print('Zodi IDL:', IDL.zodi[i])
            print('Percent err:', (1-ratio[i])*100)
            print('Day:', day_arr[i])
            print('Lon:', lon_arr[i])
            print('Lat:', lat_arr[i])
            print('\n')

        # print('\n')


Bad wave: 2.57241




Zodi Python: 0.01232
Zodi IDL: 0.01231
Percent err: 0.0811677232578134
Day: 174.27006923236505
Lon: 134.1160143888532
Lat: 1.6197384370669283



Bad wave: 2.72477




Zodi Python: 0.05492
Zodi IDL: 0.05491
Percent err: 0.018207549788351596
Day: 58.55951485984084
Lon: 343.6383970697528
Lat: 1.1286009295573365




In [12]:
get_zmod(2.57241, 'skysurf', 174.27, 134.12, 1.6, new_iso_comp=True, iso_comp_only=True)

array([0.01231])

In [6]:
0.009643/0.0096429

1.0000103703242802

In [14]:
0.15492/0.15491

1.0000645536117747